Prepare fork for use
solidwall/php_session_decoder pull request #1
Opened 2023-03-09 15:59 UTC by dsp25no

2023-03-09 16:10 UTC, dsp25no commented
С фаззингом были проблемы, почему фаззер падал на каких-то непонятных тестовых примерах. Пришлось фаззить через костыль:
```shell
while true
do
  go test -fuzz=. 2>&1 | tee /tmp/fuzz.log | grep "fuzzing process hung or terminated unexpectedly" -q && bash -c 'echo "Fuzzing failed. Restart" && rm -rf testdata/fuzz/FuzzUnserializer' || break ;
done
```

2023-04-24 18:34 UTC, WGH- requested changes

2023-04-24 18:34 UTC, WGH- commented on php_serialize/unserialize.go
> +		if strLen > UNSERIALIZABLE_OBJECT_MAX_LEN {
Do large objects cause  slowdown, unbounded memory consumption, or panics?

2023-04-24 18:34 UTC, WGH- commented on fuzz.go
>  // +build gofuzz
BTW, now that we've switched to built-in `testing` fuzzer, maybe it's time to delete gofuzz support, and move its testcases to `FuzzUnserializer` seed input?

2023-04-24 18:34 UTC, WGH- commented on php_serialize/unserialize.go
> +const UNSERIALIZABLE_OBJECT_MAX_SIZE_DEFAULT = 10 * 1024 * 1024
Snake case should not be used in Go

2023-05-22 11:40 UTC, dsp25no commented on php_serialize/unserialize.go
> +		if strLen > UNSERIALIZABLE_OBJECT_MAX_LEN {
Panics

2023-05-22 11:50 UTC, merged